baseURL = "https://rwxt.org"
title = "rwxt"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = 'spectral'
googleAnalytics = "G-T5VYH6J8WD"

[params]
fancyTitle = "rwx_t"
copyright = "Josh Moreton"
description = 'rwx technologies'
descriptionParagraph = "Read, write, execute technologies builds tech stacks for driven entrepreneurs and founders."
contactEmail = "info@rwxt.org"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/privacy-policy/'
title = "Privacy Policy"

[[params.menu.main]]
url = '/cookie-policy/'
title = "Cookie Policy"